#!/bin/bash
set -e

# magic/constant numbers and strings
HEADER_HEIGHT=1
FOOTER_HEIGHT=1
ESC="$(echo -ne "\e")"

# "pause" (relinquish) our handling of the terminal
function pause() {
    # echo terminal inputs
    stty echo
    # disable mouse events
    echo -e "\e[?1000l"
    # show the cursor
    echo -en "\e[?25h"
    # clear the screen
    cls
}

# "unpause" (take back) our handling of the terminal
function unpause() {
    # don't echo terminal inputs
    stty -echo
    # enable "extended" mouse inputs
    echo -ne "\e[?1000h\e[?1006h"
    # hide the cursor
    echo -en "\e[?25l"
    # redraw the screen
    redraw
}

# clean-up for a final exit
function shutdown() {
    pause
}
trap shutdown EXIT

# flush and discard anything in the terminal input buffer
function flush_read_buffer() {
    while read -t 0 -rs; do
        read -rsn 1
    done
}

# handle resizing of the terminal
TERM_WIDTH=80   # placeholder ... will be set correctly by initial resize
TERM_HEIGHT=40  # placeholder ... will be set correctly by initial resize
BODY_HEIGHT=38  # placeholder ... will be set correctly by initial resize
function resize() {
    # clear read buffer
    flush_read_buffer

    # clear the screen (possibly redundant, but better safe than embarrased)
    cls

    # try to position the cursor to (near) infinity
    local X=1000000
    local Y=1000000
    # set cursor pos
    echo -en "\e[${Y};${X}H"
    # request cursor location (it will have been set to the screen boundary)
    echo -en "\e[6n"
    read -rsd '[' # throw away
    read -rsd ';' TERM_HEIGHT
    read -rsd 'R' TERM_WIDTH

    BODY_HEIGHT=$((TERM_HEIGHT - HEADER_HEIGHT - FOOTER_HEIGHT))

    redraw
}
RESIZE_ON_NEXT_TICK=0
trap 'RESIZE_ON_NEXT_TICK=1' SIGWINCH

# to allow signal handling and double-clicks etc, the main loop times
# out periodically (every "tick").
# anything in this function will be executed on every tick. 
TICKS=0
function ticktock() {
    TICKS=$((TICKS + 1))

    if [ $RESIZE_ON_NEXT_TICK -eq 1 ]; then
        resize
        RESIZE_ON_NEXT_TICK=0
    fi
}

# clear/reset the terminal screen
function cls() {
    # clear the screen
    echo -en "\e[2J\e[1;1H"
    # reset colours
    echo -en "\e[0m"
}

# redraw the entire screen
function redraw() {
    # header reposition, colouring, and blanking
    echo -en "\e[1;1H\033[48;5;19m\e[2K"
    WD="$(pwd)"
    echo -en "bwc> ${WD:0:$((TERM_WIDTH - 5))}"
    echo -en "\e[0m"

    # file list area
    local END=$((BODY_HEIGHT + SCROLL_POS))
    for (( i = SCROLL_POS; i < END; i++ )); do
        redraw_line $i
    done

    # footer
    echo -en "\e[$TERM_HEIGHT;1H\033[48;5;19m\e[2K"
    echo -en " (q)uit  (s)crn_rfsh  (bskp).."

    # clear all colours
    echo -en "\e[0m"
}

# redraw a line in the file browser
function redraw_line() {
    # nothing to do if file index is outside visible area
    if [ "$1" -lt $SCROLL_POS ] || [ "$1" -gt $((SCROLL_POS + BODY_HEIGHT - 1)) ]; then
        return
    fi

    # reposition the cursor
    echo -en "\e[$(($1 - SCROLL_POS + 1 + HEADER_HEIGHT));1H"

    if [ "$1" -eq $SELECTED_FILE_INDEX ]; then
        # set the highlight colour
        echo -en "\033[48;5;57m"
    fi
    
    # blank the line (with the highlight colour)
    echo -en "\e[2K"

    local LINE="${FILE_LIST[$1]}"
    local META="${LINE%%$'\036'*}"

    local FILENAME_COLOR=""
    case "${LINE::1}" in
        l)
            FILENAME_COLOR="\033[38;5;120m"
            ;;
        d)
            if [ "$1" -eq $SELECTED_FILE_INDEX ]; then
                FILENAME_COLOR="\033[38;5;159m"
            else
                FILENAME_COLOR="\033[38;5;33m"
            fi
            ;;
    esac

    if [ ${#META} -gt $((TERM_WIDTH - 8)) ]; then
        # hide metadata due to limited terminal width
        LINE=$'\036'"${LINE##*$'\036'}"
    fi

    if [ "${#LINE}" -gt "$TERM_WIDTH" ]; then
        if [ "$1" -eq $SELECTED_FILE_INDEX ]; then
            # if the selected line is "too long",
            # attempt to show as much as possible of the filename.
            LINE="${LINE:$((${#LINE} - TERM_WIDTH))}"

            if [[ "$LINE" != *$'\036'* ]]; then
                LINE=$'\036'"$LINE"
            fi
        else
            LINE="${LINE:0:$((TERM_WIDTH - 3))}..."
        fi
    fi

    echo -en "${LINE%%$'\036'*}${FILENAME_COLOR}${LINE##*$'\036'}"
    
    # clear the colour
    echo -en "\e[0m"
}

# deal with inconsistencies in how systems output `ls -l`
function formatter() {
    # this ingests POSIX "ls -l" and reformats it how we want.
    # less portably, we could use "find -printf" (but it's not
    # available on a good number of systems).

    # discard the first line
    read -sr

    # read will chomp leading whitespace, which we want.
    cat - | tr -s ' ' | while read -sr LINE; do
        local PERMS="${LINE:0:10}"
        LINE="${LINE#* }"

        local HARDLINKS="${LINE%% *}"
        LINE="${LINE#* }"

        local OWNER="${LINE%% *}"
        LINE="${LINE#* }"
        
        local GROUP="${LINE%% *}"
        LINE="${LINE#* }"

        local BYTES="${LINE%% *}"
        LINE="${LINE#* }"

        local DATE1="${LINE%% *}"
        LINE="${LINE#* }"
        local DATE2="${LINE%% *}"
        LINE="${LINE#* }"
        local DATE3="${LINE%% *}"
        LINE="${LINE#* }"

        local FILENAME="$LINE"

        if [ ${#OWNER} -gt 9 ]; then
            OWNER="${OWNER:0:8}~"
        fi

        if [ ${#GROUP} -gt 9 ]; then
            GROUP="${GROUP:0:8}~"
        fi

        local SIZE
        if [ "$BYTES" -ge 1099511627776 ]; then
            SIZE="$((BYTES / 1099511627776))T"
        elif [ "$BYTES" -ge 1073741824 ]; then
            SIZE="$((BYTES / 1073741824))G"
        elif [ "$BYTES" -ge 1048576 ]; then
            SIZE="$((BYTES / 1048576))M"
        elif [ "$BYTES" -ge 1024 ]; then
            SIZE="$((BYTES / 1024))K"
        else
            SIZE="${BYTES}"
        fi

        # ASCII \036 (field separator) is used to delimit the filename
        printf "%s %5.5s %-9.9s %-9.9s %6.6s %3.3s %2.2s %5.5s \036%s\n" "$PERMS" "$HARDLINKS" "$OWNER" "$GROUP" "$SIZE" "$DATE1" "$DATE2" "$DATE3" "$FILENAME"

        # print on the columns we're interested in
        #printf "%s %s %s %s" "${COLS[3]}" "${COLS[4]}" "${COLS[5]}" "${COLS[6]}"
    done
}

# display a confirmation prompt for file actions
function confirm() {
    local RESULT=127

    # scroll selected file into view if it's off-screen
    scroll_to_selected

    # reposition the cursor
    echo -en "\e[$((SELECTED_FILE_INDEX - SCROLL_POS + 1 + HEADER_HEIGHT));1H"

    # set the highlight colour
    echo -en "\033[48;5;11m"

    # blank the line (with the highlight colour)
    echo -en "\e[2K"

    # display the confirmation message
    echo -n "$1 ('y' to confirm)"
    
    # clear the colour
    echo -en "\e[0m"

    read -rsn 1 ANSWER
    if [ "$ANSWER" == "y" ]; then
        RESULT=0
    fi
    flush_read_buffer

    # redraw the line back as it was
    redraw_line $SELECTED_FILE_INDEX

    return $RESULT
}

SCROLL_POS=0
CURRENT_DIRECTORY=""
FILE_LIST=()
function change_directory() {
    CURRENT_DIRECTORY="$1"
    cd "$CURRENT_DIRECTORY"
    
    # discard warnings about permission denied etc to /dev/null
    # any POSIX system should work with `ls -l`.  On fewer platforms, find could be used:
    #mapfile -t FILE_LIST < <(find . -maxdepth 1 -printf "%M %y %s %-7.7u %-7.7g %f\n" | sort -k 5 2> /dev/null)
    #mapfile -t FILE_LIST < <(POSIXLY_CORRECT=1 find . -maxdepth 1 -ls | formatter | sort -b -k 9 2> /dev/null)
    # shellcheck disable=SC2012
    mapfile -t FILE_LIST < <(LC_ALL=C ls -la | formatter 2> /dev/null)
    SCROLL_POS=0
    SELECTED_FILE_INDEX=0

    redraw
}

function is_selected_offscreen() {
    if [ $SELECTED_FILE_INDEX -lt $((SCROLL_POS + 1)) ] && [ $SCROLL_POS -gt 0 ]; then
        echo -n "-1"
    elif [ $SELECTED_FILE_INDEX -gt $((SCROLL_POS + BODY_HEIGHT - 2)) ]; then
        echo -n "1"
    else
        echo -n "0"
    fi
}

# higher-level scroll handler (notably for mouse-wheel/pgup/pgdn)
function scroll_by() {
    # allow scrolling down to a little "dead space" on the screen
    local MAX_SCROLL=$((${#FILE_LIST[@]} - 6))

    if [ "$1" -lt 0 ] && [ $SCROLL_POS -gt 0 ]; then
        SCROLL_POS=$((SCROLL_POS + $1))
        if [ $SCROLL_POS -lt 0 ]; then
            # boundary enforcement
            SCROLL_POS=0
        fi
        redraw
    elif [ "$1" -gt 0 ] && [ $SCROLL_POS -lt $MAX_SCROLL ]; then
        SCROLL_POS=$((SCROLL_POS + $1))
        if [ $SCROLL_POS -gt $MAX_SCROLL ]; then
            SCROLL_POS=$MAX_SCROLL
        fi
        redraw
    fi
}

# reposition the file browser (up/down) without changing file selection
function scroll_to_selected() {
    case "$(is_selected_offscreen)" in
        -1)
            # the screen needs to "scroll up"
            scroll_by $((SELECTED_FILE_INDEX - 1 - SCROLL_POS))
            ;;
        1)
            # the screen needs to "scroll down"
            scroll_by $((SELECTED_FILE_INDEX - BODY_HEIGHT + 2 - SCROLL_POS))
            ;;
    esac
}

# change file selection (up/down)
SELECTED_FILE_INDEX=0
PREV_SELECTED_FILE_INDEX=0
function move_by() {
    PREV_SELECTED_FILE_INDEX=$SELECTED_FILE_INDEX
    if [ "$1" -lt 0 ] && [ $SELECTED_FILE_INDEX -gt 0 ]; then
        # up
        SELECTED_FILE_INDEX=$((SELECTED_FILE_INDEX + $1))
        if [ $SELECTED_FILE_INDEX -lt 0 ]; then
            # boundary enforcement (can't select beyond 0)
            SELECTED_FILE_INDEX=0
        fi
    elif [ "$1" -gt 0 ] && [ $SELECTED_FILE_INDEX -lt $((${#FILE_LIST[@]} - 1)) ]; then
        # down
        SELECTED_FILE_INDEX=$((SELECTED_FILE_INDEX + $1))
        if [ $SELECTED_FILE_INDEX -ge ${#FILE_LIST[@]} ]; then
            # boundary enforcement (can't select beyond the end of the file list)
            SELECTED_FILE_INDEX=$((${#FILE_LIST[@]} - 1))
        fi
    fi

    if [ "$(is_selected_offscreen)" -eq 0 ]; then
        # no scrolling required, partial redraw only
        redraw_line $PREV_SELECTED_FILE_INDEX
        redraw_line $SELECTED_FILE_INDEX
    else
        scroll_to_selected
    fi
}

function move_to() {
    move_by $(($1 - SELECTED_FILE_INDEX))
}

# "file actioned" handler (user double-clicked or pressed enter and confirmed)
function action_selected() {
    local FILENAME
    FILENAME="$(get_selected_file_property "name")"

    if [ "$(get_selected_file_property "type")" == "l" ]; then
      FILENAME="$(get_selected_file_property "target")"
    fi

    if [ -d "$FILENAME" ]; then
        change_directory "$FILENAME"
    elif [ -x "$FILENAME" ]; then
        if confirm "Run ${FILENAME}?"; then
            pause
            # execute $FILENAME
            {
                set +e
                "$FILENAME"
                set -e
                
                echo " > Going back to BWC in 3 seconds..."
                sleep 3
            }
            unpause
        fi
    elif [ -r "$FILENAME" ]; then
        pause
        # read $FILENAME
        {
            less "$FILENAME"
        }
        unpause
    fi
}

# retrieve information about the selected file
function get_selected_file_property() {
    local SELECTED_FILE="${FILE_LIST[$SELECTED_FILE_INDEX]}"
    case "$1" in
        type)
            echo -n "${SELECTED_FILE::1}"
            ;;
        name)
            # ASCII \036 (field separator) is used to delimit the filename
            FILENAME="${SELECTED_FILE##*$'\036'}"
            if [ "${SELECTED_FILE::1}" == "l" ]; then
                FILENAME="${FILENAME%->*}"
            fi
            echo -n "$FILENAME"
            ;;
        target)
            if [ "${SELECTED_FILE::1}" != "l" ]; then
                echo -n ""
            fi
            echo -n "${SELECTED_FILE##*-> }"
            ;;
        *)
            echo "Unsupported file property" 1>&2
            ;;
    esac
}

# start-up
resize
change_directory "$(pwd)"
unpause

# main loop
ESC_CODE=""
TICKTOCK=0
LAST_CLICK_TICKS=-1
LAST_CLICKED_FILE_INDEX=-1
# note -t essentially sets double click speed, as well as visual refresh of clocks etc
while read -t 0.5 -rs -N 1 CHAR || TICKTOCK=1; do
    # nothing in the terminal input buffer.
    if [ $TICKTOCK -eq 1 ]; then
        TICKTOCK=0
        ticktock
        continue
    fi

    # input debug
    #printf "%3d" "'$CHAR"

    if [ "$CHAR" == "$ESC" ]; then
        # start of escape sequence
        ESC_CODE="$ESC"
    elif [ -n "$ESC_CODE" ]; then
        # continuation of escape sequence
        ESC_CODE="${ESC_CODE}${CHAR}"
        CLEAR_ESC_CODE=1
        case "$ESC_CODE" in
            "${ESC}[<")
                # mouse event
                read -rsd ';' EVENT
                read -rsd ';' X
                read -rsn 1 Y
                read -rsn 1 C
                case "$C" in
                    [mM])
                        M="$C"
                        ;;
                    *)
                        Y="${Y}${C}"
                        read -rs -N 1 M
                        ;;
                esac

                # movecur 
                #echo -ne "\nMOUSE $EVENT $M ( $X, $Y )"
                case "$M" in
                    M)
                        # mouse "down"
                        case "$EVENT" in
                            64)
                                # scroll up
                                scroll_by -1
                                ;;
                            65)
                                # scroll down
                                scroll_by 1
                                ;;
                        esac
                        ;;
                    m)
                        # mouse "up"
                        CLICKED_FILE_INDEX=$((SCROLL_POS + Y - 1 - HEADER_HEIGHT))

                        if [ $TICKS -eq $LAST_CLICK_TICKS ] && [ $LAST_CLICKED_FILE_INDEX -eq $CLICKED_FILE_INDEX ]; then
                            # double click
                            action_selected

                            # clear double-click
                            LAST_CLICK_TICKS=-1
                        else
                            # single click
                            move_to $CLICKED_FILE_INDEX
                        fi

                        LAST_CLICKED_FILE_INDEX=$CLICKED_FILE_INDEX
                        LAST_CLICK_TICKS=$TICKS
                        ;;
                esac
                ;;
            
            "${ESC}[A")
                # UP
                move_by -1
                ;;

            "${ESC}[B")
                # DOWN
                move_by 1
                ;;

            "${ESC}[C")
                # RIGHT
                ;;

            "${ESC}[D")
                # LEFT
                ;;
            
            "${ESC}[5~")
                # PGUP
                move_by $((0 - BODY_HEIGHT + 1))
                ;;

            "${ESC}[5;5~")
                # ^PGUP
                scroll_by $((0 - BODY_HEIGHT + 1))
                ;;

            "${ESC}[6~")
                # PGDOWN
                move_by $((BODY_HEIGHT - 1))
                ;;

            "${ESC}[6;5~")
                # ^PGDOWN
                scroll_by $((BODY_HEIGHT - 1))
                ;;

            *)
                CLEAR_ESC_CODE=0

                # TODO - allow custom keybindings

                if [ ${#ESC_CODE} -gt 10 ]; then
                    echo "SOMETHING BROKE #1: $ESC_CODE"
                fi
            ;;
        esac

        if [ $CLEAR_ESC_CODE -eq 1 ]; then
            ESC_CODE=""
        fi
    else
        # any other input

        # input debug
        #printf "%3d" "'$CHAR"

        case "$CHAR" in
            s)
                cls
                redraw
                ;;
            q)
                exit
                ;;
            $'\n')
                # enter key
                action_selected
                ;;
            $'\x7F')
                # backspace
                change_directory '..'
                ;;
            *)
                # keypress
                echo -ne "$CHAR"
                # TODO - allow custom keybindings
                ;;
        esac
    fi
done
